// <auto-generated />
using System;
using CQRSDemo.Models.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQRSDemo.Migrations
{
    [DbContext(typeof(CustomerSQLiteDatabaseContext))]
    [Migration("20190227193312_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CQRSDemo.Models.CustomerRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CQRSDemo.Models.PhoneRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AreaCode");

                    b.Property<long?>("CustomerRecordId");

                    b.Property<int>("Number");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CustomerRecordId");

                    b.ToTable("PhoneRecord");
                });

            modelBuilder.Entity("CQRSDemo.Models.PhoneRecord", b =>
                {
                    b.HasOne("CQRSDemo.Models.CustomerRecord")
                        .WithMany("Phones")
                        .HasForeignKey("CustomerRecordId");
                });
#pragma warning restore 612, 618
        }
    }
}
